name: Deploy

on:
  workflow_run:
    workflows: ["Integration Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "space-delimited"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if specific subdirectories have changes
        id: check_subdir
        run: |
          CHANGED_FILES="${{ steps.files.outputs.all }}"
          SUBDIRS=("code/" "config.py")
          SUBDIR_CHANGED="false"
          for dir in "${SUBDIRS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "$dir"; then
              SUBDIR_CHANGED="true"
              break
            fi
          done

          echo "SUBDIR_CHANGED=$SUBDIR_CHANGED" >> $GITHUB_ENV

      - name: Set up Python
        if: env.SUBDIR_CHANGED == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        if: env.SUBDIR_CHANGED == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload Model to S3
        if: env.SUBDIR_CHANGED == 'true'
        run: |
          python upload_model_s3.py
        env:
          SAGEMAKER_ROLE: ${{ secrets.SAGEMAKER_ROLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create Sagemaker Endpoint
        if: env.SUBDIR_CHANGED == 'true'
        run: |
          python create_endpoint.py
        env:
          SAGEMAKER_ROLE: ${{ secrets.SAGEMAKER_ROLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
